name: Deploy Website to AWS S3

on:
  push:
    branches:
      - master

jobs:
  test-and-deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # - name: Run basic tests
      #   run: |
      #     test -f index.html
      #     test -f style.css
      #     test -f script.js
      #     grep -q "DevOps Training" index.html

      - name: Deploy website to S3
        run: |
          aws s3 sync . s3://${{ secrets.S3_BUCKET }} \
            --exclude ".git/*" \
            --exclude ".github/*"

      - name: Verify deployment
        run: |
          aws s3 ls s3://${{ secrets.S3_BUCKET }}